services:
  - type: web
    name: a100-azs-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PORT
        value: 8000
